name: service tests

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - '**/README.md'

jobs:
  test:
    name: Unit-Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Verify
        run: mvn -B clean verify
        env:
          mongodb_test_uri:  ${{ secrets.MONGODB_TEST_URI }}
          test_email: ${{ secrets.TEST_EMAIL }}
          test_email_pwd: ${{ secrets.TEST_EMAIL_PWD }}
